# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    status_completed:
        label: indikator.marketing::lang.button.completed
        type: checkbox
        conditions: status = 1

    status_uncompleted:
        label: indikator.marketing::lang.button.uncompleted
        type: checkbox
        conditions: status = 2 in (:filtered)

    priority1:
        label: indikator.marketing::lang.priority.higt
        type: checkbox
        conditions: priority = 1

    priority2:
        label: indikator.marketing::lang.priority.normal
        type: checkbox
        conditions: priority = 2

    priority3:
        label: indikator.marketing::lang.priority.low
        type: checkbox
        conditions: priority = 3

    client:
        label: indikator.marketing::lang.form.client
        modelClass: Indikator\Marketing\Models\Client
        nameFrom: name
        conditions: client_id in (:filtered)

    project:
        label: indikator.marketing::lang.form.project
        modelClass: Indikator\Marketing\Models\Project
        nameFrom: name
        conditions: project_id in (:filtered)

    created_date:
        label: indikator.marketing::lang.form.created
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    updated_date:
        label: indikator.marketing::lang.form.updated
        type: daterange
        conditions: updated_at >= ':after' AND updated_at <= ':before'
